# Generated by Django 3.2.5 on 2022-08-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_registration',
            fields=[
                ('regiid', models.IntegerField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('RollNumber', models.IntegerField()),
                ('Standard', models.IntegerField()),
                ('ClassSec', models.CharField(max_length=8)),
                ('mobile', models.BigIntegerField()),
                ('password', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='teacher_registration',
            fields=[
                ('regiid', models.IntegerField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('Subject', models.CharField(max_length=20)),
                ('classThought', models.CharField(max_length=10)),
                ('contactNumb', models.BigIntegerField()),
                ('password', models.CharField(max_length=24)),
            ],
        ),
    ]
