# Generated by Django 3.2.5 on 2022-08-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileView', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_registration',
            name='personis',
            field=models.CharField(default='Student', max_length=15),
        ),
        migrations.AddField(
            model_name='teacher_registration',
            name='personis',
            field=models.CharField(default='Teacher', max_length=15),
        ),
    ]
